// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZOO_Management.Infrastructure.Models;

public partial class Posjetitelj
{
    public int IdPosjetitelj { get; set; }

    public int? IdKorisnik { get; set; }

    public DateTime? RegistriranOd { get; set; }

    public int? Kontakt { get; set; }

    public virtual Korisnik IdKorisnikNavigation { get; set; }

    public virtual ICollection<Ulaznica> Ulaznica { get; set; } = new List<Ulaznica>();
}