// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZOO_Management.Infrastructure.Models;

public partial class Sektor
{
    public int IdSektor { get; set; }

    public int? Povrsina { get; set; }

    public string Naziv { get; set; }

    public virtual ICollection<Nastamba> Nastamba { get; set; } = new List<Nastamba>();
}