// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZOO_Management.Infrastructure.Models;

public partial class VrstaZivotinje
{
    public int IdVrsta { get; set; }

    public string Boja { get; set; }

    public int? Visina { get; set; }

    public int? ZivotniVijek { get; set; }

    public virtual ICollection<Zivotinja> Zivotinja { get; set; } = new List<Zivotinja>();
}