// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZOO_Management.Data.Models;

public partial class Stvar
{
    public int IdStvar { get; set; }

    public int? SerijskiBroj { get; set; }

    public string Vrsta { get; set; }

    public string Opis { get; set; }

    public int? Cijena { get; set; }

    public virtual ICollection<StvarInventar> StvarInventar { get; set; } = new List<StvarInventar>();
}