// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZOO_Management.Data.Models;

public partial class StvarInventar
{
    public int IdStvar { get; set; }

    public int IdInventar { get; set; }

    public int? Kolicina { get; set; }

    public virtual Inventar IdInventarNavigation { get; set; }

    public virtual Stvar IdStvarNavigation { get; set; }
}