// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZOO_Management.Data.Models;

public partial class Ulaznica
{
    public int IdUlaznica { get; set; }

    public int? IdPosjetitelj { get; set; }

    public int? Cijena { get; set; }

    public DateTime? Datum { get; set; }

    public virtual ICollection<Dogadaj> Dogadaj { get; set; } = new List<Dogadaj>();

    public virtual Posjetitelj IdPosjetiteljNavigation { get; set; }
}